version: '3.8'

services:
  db:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Favorite@movies!
      - POSTGRES_DB=favorite_movies_db
    volumes:
      - postgres_data:/bitnami/postgresql

  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    env_file: 
      - ./backend/.env  
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    env_file:
      - ./frontend/.env.local 
    depends_on:
      - backend

volumes:
  postgres_data:
