version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/bitnami/postgresql
    networks:
    - movie-network

  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    env_file: 
      - ./backend/.env  
    depends_on:
      - postgres
    networks:
      - movie-network

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    env_file:
      - ./frontend/.env.local 
    depends_on:
      - backend

networks:
  movie-network:
    name: movie-network
    driver: bridge


volumes:
  postgres_data:
