version: '3'

services:
# Serviço para banco de dados PostgreSQL
  db:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Favorite@movies!
      - POSTGRES_DB=favorite_movies_db
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: